# Generated by Django 5.1.5 on 2026-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='trip_type',
            field=models.CharField(choices=[('UP', 'Up-trip (To Campus)'), ('DOWN', 'Down-trip (From Campus)')], default='UP', max_length=4),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
